# Generated by Django 4.2 on 2024-08-12 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de creación",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de modificación"
            ),
        ),
    ]
