# Generated by Django 4.2 on 2024-08-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_usuario_created_usuario_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="created",
        ),
    ]
